name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    #if: "contains(github.event.head_commit.message, 'deploy application')"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
          fetch-depth: '0'

    - name: Generate Git Tag
      id: generate_tag
      run: |
        # get latest tag
        version=$(git describe --tags `git rev-list --tags --max-count=1`)
        # print latest
        echo $version
        NEW_TAG=$(echo "$version" | awk 'BEGIN{FS=OFS="."} {$4+=1} 1')
        echo "Generated new tag: $NEW_TAG"
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

    - name: Push Git Tag
      run: |
        git tag $NEW_TAG
        git push origin $NEW_TAG
